# Generated by Django 5.1 on 2026-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('response_set', 'question'), name='unique_response_per_question'),
        ),
    ]
