# Generated by Django 5.1.15 on 2026-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='Defines if this questionnaire is the initial screening for group assignment'),
        ),
    ]
