# Generated by Django 5.1 on 2026-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_response_unique_response_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_posttest',
            field=models.BooleanField(default=False, help_text='Defines if this questionnaire is the Day 7 post-test reassessment'),
        ),
    ]
