# Generated by Django 5.1 on 2026-05-07 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnaire_is_posttest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='responseset',
            index=models.Index(fields=['status', 'completed_at'], name='idx_rs_status_completed'),
        ),
        migrations.AddIndex(
            model_name='responseset',
            index=models.Index(fields=['user', 'status'], name='idx_rs_user_status'),
        ),
    ]
