# Generated by Django 5.1 on 2026-05-24 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_responseset_idx_rs_status_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='assessment_type',
            field=models.CharField(choices=[('SOCIODEMOGRAPHIC', 'Sociodemographic Form'), ('PSYCHOMETRIC', 'Psychometric Battery')], default='PSYCHOMETRIC', max_length=20),
        ),
        migrations.AddField(
            model_name='responseset',
            name='milestone',
            field=models.CharField(blank=True, choices=[('SIGNUP', 'Signup Baseline'), ('7_DAYS', '7 Days Post-Test'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year')], db_index=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='responseset',
            index=models.Index(fields=['user', 'milestone', 'status'], name='idx_rs_user_milestone_status'),
        ),
        migrations.AddConstraint(
            model_name='responseset',
            constraint=models.UniqueConstraint(fields=('user', 'questionnaire', 'milestone'), name='unique_user_questionnaire_milestone'),
        ),
    ]
