# Generated by Django 5.1 on 2026-04-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequence number for daily tasks', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_activities', to='groups.group'),
        ),
    ]
