# Generated by Django 5.1 on 2026-05-03 06:28

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_submission_experiment_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('submission_date'), models.F('user'), name='unique_daily_submission_per_user'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'experiment_day'), name='unique_user_experiment_day'),
        ),
    ]
