# Generated by Django 5.1 on 2026-05-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_submission_experiment_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_daily_submission_per_user',
        ),
    ]
