# Generated by Django 5.1 on 2026-05-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Reply sent to the user', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_read_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
