# Generated by Django 5.1 on 2026-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_posttest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='posttest_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
